### ISSUE TITLE
Implement Streaming Interface

### ISSUE THREAD

**Issue by BenBE** [kjdev/php-ext-zstd#12]
Please implement a streaming interface as documented in the original zstd library:
https://github.com/facebook/zstd/blob/255597502c3a4ef150abc964e376d4202a8c2929/lib/zstd.h#L247

Ideally this should be published as stream handling class, so it can be used as a protocol handler, cf. http://php.net/manual/de/stream.streamwrapper.example-1.php

**Comment by remicollet** [comment]
can be close... implemented in 0.7.0

**Comment by glensc** [comment]
@remicollet probably wanted to say "can be closed, implemented in 0.7.0"

**Comment by tzukav** [comment]
Is there any way to use compression level with streams?

**Comment by BenBE** [comment]
> Is there any way to use compression level with streams?

Have a look at the [test case](https://github.com/kjdev/php-ext-zstd/pull/17/commits/c529117819389455825e068ed77e096f6abe02bf#diff-42a82a40974c5436771b12da4a6b0fc2ddd2750f3d27fc60cb590fda6a5f442aR17-R23) …
