### ISSUE TITLE
Windows release

### ISSUE THREAD

**Issue by marcing** [kjdev/php-ext-zstd#14]
Hi!

Since zstd is available also on Windows, would you consider releasing your extension on https://pecl.php.net/ together with dll's? 

Thank you,
Marcin

**Comment by kjdev** [comment]
We are not examining because the Windows Build environment is not ready.

**Comment by marcing** [comment]
If in future it's possible to provide way of compiling .dll for Windows I would be grateful. Thank you.

**Comment by remicollet** [comment]
@kjdev I also think than publishing this extension on pecl will give it more visibility, so more users (and I can probably help on this)

@weltling @cmb39 would you have some spare time to look at the config.w32 ?

probably better to use the shared `libzstd` if available (but as I can see `rdkafka` extension DLL, it is probably already there)

**Comment by cmb69** [comment]
Sorry for being late, but I didn't get the notification (my handle is @cmb69). Anyhow, PR #33 should provide the basics for having Windows DLLs on the PECL Website. These builds should be triggered as soon as a new version with config.w32 is released.

**Comment by kjdev** [comment]
PR #33 was imported and a new version (0.9.0) was created.

Windows DLLs are now also created.

https://pecl.php.net/package/zstd

**Comment by marcing** [comment]
So cool. Thanks!!!
