### ISSUE TITLE
Add a function or constant that gets maxLevel

### ISSUE THREAD

**Issue by xywf221** [kjdev/php-ext-zstd#15]
Hello @kjdev I encountered a problem when I used the zstd_compress function. I don't know how to enter the value of the level. I read the source code and found that the level should be filled with `level > maxLevel` but maxLevel is obtained by ZSTD_maxCLevel. Can you add a new function or constant to get the value of maxLevel?

**Comment by kjdev** [comment]
9ff70771c05dd0ff7730abe35f3282d1ee815976

- ZSTD_COMPRESS_LEVEL_MIN
- ZSTD_COMPRESS_LEVEL_MAX
- ZSTD_COMPRESS_LEVEL_DEFAULT

Added 3 constants.

**Comment by xywf221** [comment]
@kjdev thank you for your update
