### ISSUE TITLE
Warning: zstd_compress: compression level (100) must be within 1..22 or smaller then 0

### ISSUE THREAD

**Issue by glensc** [kjdev/php-ext-zstd#29]
- http://buildlogs.pld-linux.org//index.php?dist=th&arch=x86_64&ok=0&name=php-pecl-zstd&id=b1b35069-2689-444f-b45e-b42073a6afde&action=tail

For me this test fails for php 5.3-5.6, 7.0-7.3, passes on 7.4

```
TEST 10/24 [tests/008.phpt]
========DIFF========
028+ Warning: zstd_compress: compression level (100) must be within 1..22 or smaller then 0 in /tmp/B.lZPARi/BUILD/php73-pecl-zstd-0.8.0/tests/008.php on line 6
029+ 100 -- 0 --
030+ Warning: zstd_uncompress: it was not compressed by zstd in /tmp/B.lZPARi/BUILD/php73-pecl-zstd-0.8.0/tests/008.php on line 8
031+ false
032+ -1 -- 2674 -- true
033+ 0 -- 3547 --
034+ Warning: zstd_uncompress: it was not compressed by zstd in /tmp/B.lZPARi/BUILD/php73-pecl-zstd-0.8.0/tests/008.php on line 8
035+ false
028- Warning: zstd_compress: compression level (100) must be within 1..22 in %s on line %d
029- 100 -- 0 -- false
030-
031- Warning: zstd_compress: compression level (-1) must be within 1..22 in %s on line %d
032- -1 -- 0 -- false
033- 0 -- 3547 -- false
```

Build logs:
- [7.4](http://buildlogs.pld-linux.org//index.php?dist=th&arch=x86_64&ok=0&name=php-pecl-zstd&id=2c8bc259-054c-4501-bf1e-286acde23cff&action=tail)
- [7.3](http://buildlogs.pld-linux.org//index.php?dist=th&arch=x86_64&ok=0&name=php-pecl-zstd&id=b1b35069-2689-444f-b45e-b42073a6afde&action=tail)
- [7.2](http://buildlogs.pld-linux.org//index.php?dist=th&arch=x86_64&ok=0&name=php-pecl-zstd&id=b2941aa6-2229-4bac-ac62-8170a499d00f&action=tail)
- [7.1](http://buildlogs.pld-linux.org//index.php?dist=th&arch=x86_64&ok=0&name=php-pecl-zstd&id=568ab343-8921-4769-a1e3-117859c28d34&action=tail)
- [7.0](http://buildlogs.pld-linux.org//index.php?dist=th&arch=x86_64&ok=0&name=php-pecl-zstd&id=43c44fad-395a-4768-aa53-8082a82f35da&action=tail)
- [5.6](http://buildlogs.pld-linux.org//index.php?dist=th&arch=x86_64&ok=0&name=php-pecl-zstd&id=08557982-abdf-481e-b3a3-02076825f5c3&action=tail)
- [5.5](http://buildlogs.pld-linux.org//index.php?dist=th&arch=x86_64&ok=0&name=php-pecl-zstd&id=5886efd8-ac57-4352-82aa-f192fd62ce2c&action=tail)
- [5.4](http://buildlogs.pld-linux.org//index.php?dist=th&arch=x86_64&ok=1&name=php-pecl-zstd&id=13b7b15c-30aa-49cd-8f5d-2597808b39ae&action=tail)
- [5.3](http://buildlogs.pld-linux.org//index.php?dist=th&arch=x86_64&ok=0&name=php-pecl-zstd&id=e916eaf1-5b52-4be7-9d76-88b70a2899e2&action=tail)

**Comment by kjdev** [comment]
409e920  Fixed a problem with libzstd's version output.
