### ISSUE TITLE
Add PHP 8.0 DLLs on PECL

### ISSUE THREAD

**Issue by Dibbyo456** [kjdev/php-ext-zstd#37]
Currently the Windows DLLs on PECL repo are 7.2. to 7.4. Add PHP 8.0 please since it's now stable.

**Comment by kjdev** [comment]
This will be the DLL created by CI.

[Non Thread Safe (NTS) x64](https://github.com/kjdev/php-ext-zstd/files/5741042/php_zstd-8.0-nts-vs16-x64.zip)
[Thread Safe (TS) x64](https://github.com/kjdev/php-ext-zstd/files/5741043/php_zstd-8.0-ts-vs16-x64.zip)
[Non Thread Safe (NTS) x86](https://github.com/kjdev/php-ext-zstd/files/5741047/php_zstd-8.0-nts-vs16-x86.zip)
[Thread Safe (TS) x86](https://github.com/kjdev/php-ext-zstd/files/5741046/php_zstd-8.0-ts-vs16-x86.zip)

**Comment by kjdev** [comment]
https://pecl.php.net/package/zstd/0.10.0/windows

Created in a new version (0.10.).
