### ISSUE TITLE
zstd on windows

### ISSUE THREAD

**Issue by mmojadad** [kjdev/php-ext-zstd#43]
Hi
I modified php.ini as following but i can not see zstd in phpinfo.php report. How can be sure extension is enabled?
php_zstd.dll NTS placed in C:\Program Files\PHP\v7.4.24\ext

[PHP_Zstandard]
zend_extension=php_zstd.dll

**Comment by kjdev** [comment]
- Is the `extension_dir` correct (you may have the wrong reference)
- Are there any error or warning messages (you may be using the wrong version)

**Comment by mmojadad** [comment]
> * Is the `extension_dir` correct (you may have the wrong reference)
> Yes, Sure. All other extensions like Zend OPcache v7.4.24 there working fine!
>     * Are there any error or warning messages (you may be using the wrong version)
Yes, As following 
PHP Warning:  Failed loading Zend extension 'php_zstd.dll' (tried: C:\Program Files\PHP\v7.4.24\ext\php_zstd.dll (The specified module could not be found.), C:\Program Files\PHP\v7.4.24\ext\php_php_zstd.dll.dll (The specified module could not be found.)) in Unknown on line 0

Zend Extension Build | API320190902,NTS,VC15
PHP Extension Build | API20190902,NTS,VC15
------------- dll -----------
File version : 7.4.21.0
Product version: 7.4.21-dev

**Comment by ranvis** [comment]
For the build available in pecl.php.net, libzstd.dll must be in the PHP executable directory (or whereever Windows can find,) while php_zstd.dll should still be in ext/.

**Comment by mmojadad** [comment]
@ranvis 
Already php_zstd.dll is in C:\Program Files\PHP\v7.4.24\ext\

**Comment by ranvis** [comment]
If the distribution has `libzstd.dll`, then that DLL is required for Windows to _load_ `php_zstd.dll`.
And Windows cannot find `libzstd.dll` if it is in `ext/` directory.
Try moving it to the same directory as php.exe.

**Comment by mmojadad** [comment]
@ranvis
Yes! I moved libzstd.dll to the same directory as php.exe and now working fine. Thanks
