### ISSUE TITLE
Is an "ob_zstdhandler" function possible?

### ISSUE THREAD

**Issue by Ys88** [kjdev/php-ext-zstd#71]
Hi!

Firstly congratulations, this a great extension (as well as your others).

I was wondering if you think it could be possible to have an ob_zstdhandler function similar to the ob_gzhandler? 

zstd_compress works great with ob_start, but only if the whole page is compressed at once. 

If we set a chunk_size when calling ob_start, or if we call ob_flush before ob_end_flush, we can't use zstd_compress.

Using chunk_size or/and ob_flush allows to send data early, so the client can start rendering the page, without having to wait for the entire page to be generated server side.

If this is possible, I think it would be a terrific feature. 

Regards,

Edit: I don't know if my question is related to this request [Support incremental compression and decompression](https://github.com/kjdev/php-ext-zstd/issues/64).

**Comment by kjdev** [comment]
https://github.com/kjdev/php-ext-zstd/commit/e8575621e406e8f431e71c231473ba777d7d9324 add output handler (PHP 8.0+).

``` php
ini_set('zstd.output_compression', 'On');
// OR
// ob_start('ob_zstd_handler');

echo ...;
```

**Comment by kjdev** [comment]
release: https://github.com/kjdev/php-ext-zstd/tree/refs/tags/0.14.0
